source 'https://rubygems.org'

gem 'bigdecimal'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-daterangepicker-rails'
gem 'bootstrap-sass'
gem 'bootstrap-wysihtml5-rails'
gem 'byebug'
gem 'coffee-rails', '~> 4.1.0'
gem 'fastclick-rails'
gem 'font-awesome-rails'
gem 'font-ionicons-rails'
gem 'haml-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-datatables-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'js-routes'
gem 'momentjs-rails'
gem 'nokogiri', '1.6.6.2'
gem 'rails', '4.2.3'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'select2-rails'
gem 'spring'
gem 'sqlite3', '1.3.10'
gem 'uglifier', '>= 1.3.0'
gem 'web-console', '~> 2.0'
