source 'https://rubygems.org'

gem 'bootstrap-datepicker-rails'
gem 'bootstrap-daterangepicker-rails'
gem 'bootstrap-sass'
gem 'bootstrap-wysihtml5-rails'
gem 'byebug'
gem 'coffee-rails'
gem 'fastclick-rails'
gem 'font-awesome-rails'
gem 'font-ionicons-rails'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-datatables-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'js-routes'
gem 'momentjs-rails'
gem 'rails'
gem 'sass-rails'
gem 'sdoc', group: :doc
gem 'select2-rails'
gem 'spring'
gem 'sqlite3'
gem 'uglifier'
gem 'web-console'
